logging.structured.format.console=ecs
logging.level.root=INFO
logging.level.com.fitlake=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=OFF

